# Generated by Django 5.1.2 on 2024-11-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='comentarios',
            new_name='comentario',
        ),
    ]
